version: "3"
services:
  neo4j:
    image: "neo4j/neo4j-experimental:4.0.0-rc01"
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/import:/var/lib/neo4j/import
      - ./data/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH
      - "NEO4J_dbms_connector_bolt_advertised__address=${NEO4J_URL}"
  postgres:
    image: "postgres:12.1"
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
